### PR TITLE
CSNF Splunk Technology Add-on 1.0.0

### PR DESCRIPTION
**Pull request by ghost**
# This is the initial release of the CSNF Splunk Technology Add-on. 
## Purpose
- The purpose of the CSNF Splunk Technology Add-on is to provide a set of common attribute mappings in support of multi-cloud enterprise security SIEM and SOAR operations.

## Who is this app for? #
- The primary audience for this application are security detection engineering teams who wish to integrate CSNF within their multi cloud security landing zone.

## How does the app work? #
- It works by mapping keys and values provided by your configured cloud provider to a set of CSNF common properties. The CSNF's canonical data model standardizes alerts received from multiple cloud and SaaS providers that can be used as inputs by the SOC for common security workflows. 

## Support
- Currently the only requirement is that the user have the AWS Technology Add-on configured in their Splunk Environment.

### CODE REVIEW

**Review by michaelthomasclark — DISMISSED** [review]

**Comment by michaelthomasclark** [comment]
Reviewed and approved.

**Review by Halimer — APPROVED** [review]
Reviewed

**Review by michaelthomasclark — APPROVED** [review]

**Comment by michaelthomasclark** [comment]
And another one.

**Comment by michaelthomasclark** [comment]
{Not a coder;

**Pull request merged**
