### PR TITLE
Add GCP Security Command Center Mappings

### PR DESCRIPTION
**Pull request by rjulian**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] Take a minute to review the [code of conduct](Covenant_Code_of_Conduct.md).
- [ ] Check your code additions will fail neither code linting checks nor unit test.

### Terms and conditions for use, reproduction and distribution
🚨 [Apache License](LICENSE.txt).

### Description
Added GCP SCC Mappings.

💔Thank you from the Automated Cloud Governance Working Group at ONUG!

### CODE REVIEW

**Comment by rjulian** [comment]
Solves #44

**Review by Halimer — APPROVED** [review]
GCP Command Center mappings

**Review by Halimer — APPROVED** [review]
Command Center Mappings

**Review by Halimer — APPROVED** [review]

**Review by Halimer — APPROVED** [review]
Approving

**Review by Halimer — APPROVED** [review]
GCP mappings

**Review by Halimer — DISMISSED** [review]

**Comment by rjulian** [comment]
Got Josh's approval and it keeps getting auto stopped.

**Pull request merged**
